
services:
  # SECURITY-HARDENED: Blockchain recovery analysis environment
  blockchain-recovery:
    build: .
    container_name: social-node-recovery-analysis-secure
    ports:
      - "127.0.0.1:4080:4080"  # SECURITY: Bind only to localhost
      - "127.0.0.1:2222:2222"  # SECURITY: SSH on non-standard port, localhost only
    volumes:
      # SECURITY: Read-only mounts where possible
      - ./src:/home/recovery/workspace/src:ro
      - ./config:/home/recovery/workspace/config:ro
      # SECURITY: Separate writable volumes
      - blockchain_analysis_data:/home/recovery/workspace/data
      - recovery_notebooks:/home/recovery/workspace/notebooks
    networks:
      - recovery-net
    environment:
      - RECOVERY_MODE=secure_blockchain_analysis
      - SECURITY_LEVEL=HIGH
      - NO_INTERNET_ACCESS=true
    # SECURITY: Remove network access during sensitive operations
    network_mode: "none"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    command: 
      - bash
      - -c
      - "echo 'SECURE Blockchain Recovery Analysis Ready - Network Isolated' && echo 'Security Level: HIGH - Air-Gapped Mode' && tail -f /dev/null"

networks:
  recovery-net:
    driver: bridge
    # SECURITY: Isolated internal network
    internal: true
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  # SECURITY: Named volumes for sensitive data
  blockchain_analysis_data:
    driver: local
  recovery_notebooks:
    driver: local
